#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: Hotel-Service
  config:
    import: configserver:http://localhost:9094
  profiles:
    active: dev